"""
Convert all PNG publication figures to 600-DPI TIFF.

Reads every .png in 06_figures/publication/ and writes a companion .tif
with 600-DPI metadata. Also assembles Figure_S2_fes from the two per-system
FES convergence plots (S1 BIN1 BAR and S3 PICALM ANTH) generated by
01_analyze_fes_convergence.py.

Note: run 01_analyze_fes_convergence.py before this script to ensure the
FES source plots are at 600 DPI.

Output naming:
  06_figures/publication/<stem>.tif   (overwrites existing TIFs)

Usage:
  python3 09_scripts/10_figures/09_convert_to_tiff_600dpi.py
  python3 09_scripts/10_figures/09_convert_to_tiff_600dpi.py --project-root /path/to/CRYPTAD
"""

import argparse
from pathlib import Path
from PIL import Image

TARGET_DPI = 600

# Figure_06 is now generated by 10_ibufenac_drift_figure.py and already
# written directly to publication/ — no manual copy needed here.
MANUAL_FIGURES: dict = {}

_script       = Path(__file__).resolve()
_default_root = _script.parents[2]


def convert(src: Path, dst: Path) -> None:
    img = Image.open(src).convert("RGB")
    img.save(dst, dpi=(TARGET_DPI, TARGET_DPI), compression="tiff_lzw")
    print(f"  {src.name:45s} → {dst.name}  ({img.width}×{img.height} px @ {TARGET_DPI} dpi)")


def assemble_fes(root: Path, pub_dir: Path) -> None:
    """Tile BIN1 BAR and PICALM ANTH FES convergence plots side-by-side → Figure_S2."""
    meta_dir = root / "03_pocket_analysis" / "metadynamics"
    s1  = meta_dir / "fes_convergence_S1_BIN1_BAR.png"
    s3  = meta_dir / "fes_convergence_S3_PICALM_ANTH.png"

    if not s1.exists() or not s3.exists():
        print(f"  [SKIP] FES source plots missing — run 01_analyze_fes_convergence.py first")
        return

    img1 = Image.open(s1).convert("RGB")
    img3 = Image.open(s3).convert("RGB")

    # Normalise heights to the taller of the two
    h = max(img1.height, img3.height)
    if img1.height != h:
        img1 = img1.resize((int(img1.width * h / img1.height), h), Image.LANCZOS)
    if img3.height != h:
        img3 = img3.resize((int(img3.width * h / img3.height), h), Image.LANCZOS)

    GAP = 20
    canvas = Image.new("RGB", (img1.width + GAP + img3.width, h), (255, 255, 255))
    canvas.paste(img1, (0, 0))
    canvas.paste(img3, (img1.width + GAP, 0))

    out_png = pub_dir / "Figure_S2_fes.png"
    out_tif = pub_dir / "Figure_S2_fes.tif"
    canvas.save(out_png, dpi=(TARGET_DPI, TARGET_DPI))
    canvas.save(out_tif, dpi=(TARGET_DPI, TARGET_DPI), compression="tiff_lzw")
    print(f"  {'FES assembly':45s} → Figure_S2_fes.{{png,tif}}  "
          f"({canvas.width}×{canvas.height} px @ {TARGET_DPI} dpi)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert publication PNGs to 600-DPI TIFF")
    parser.add_argument("--project-root", default=str(_default_root))
    args = parser.parse_args()

    root    = Path(args.project_root).resolve()
    pub_dir = root / "06_figures" / "publication"

    print(f"Source:  {pub_dir.relative_to(root)}")
    print(f"Target:  {pub_dir.relative_to(root)}  (same folder, .tif suffix)\n")

    converted = 0

    # Convert all PNGs already in publication/ (skip Figure_S2 — assembled separately)
    for src in sorted(pub_dir.glob("Figure_*.png")):
        if "Figure_S2_fes" in src.name:
            continue
        dst = src.with_suffix(".tif")
        convert(src, dst)
        converted += 1

    # Assemble Figure_S2 from per-system FES convergence plots
    print("\nAssembling Figure_S2_fes from FES convergence plots:")
    assemble_fes(root, pub_dir)
    converted += 1

    print(f"\nTotal: {converted} files written")


if __name__ == "__main__":
    main()
